# Generated by Django 5.1.7 on 2025-03-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_popularcourses_courselisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('country_image', models.ImageField(blank=True, null=True, upload_to='free_education/')),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
    ]
