# Generated by Django 5.1.7 on 2025-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_freeeducation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselisting',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='freeeducation',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='popularcourses',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='courselisting',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freeeducation',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popularcourses',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courselisting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freeeducation',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freeeducation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='popularcourses',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
