# Generated by Django 5.1.7 on 2025-03-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newsandevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('help_type', models.CharField(choices=[('education', 'Education'), ('job_assistance', 'Job Assistance'), ('migration', 'Migration')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEventsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_events/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Details Link')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEventsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ServiceBanner',
            new_name='Service',
        ),
        migrations.DeleteModel(
            name='NewsAndEvents',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='apply_now_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='contact_us_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsandeventsdetail',
            name='news_and_events_overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.newsandeventsoverview'),
        ),
        migrations.AddField(
            model_name='testimonialdetail',
            name='testimonial_overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.testimonialoverview'),
        ),
    ]
